In [1]:
import numpy as np

##### 課題1

行列積は、左から行ベクトル、右から烈ベクトルを掛け算する

$$
    % "boldsymbol"で太字にしている
    \boldsymbol{X} =
        % ベクトルや行列は"left["と"right]"でベクトルや行列の括弧を作る
        % 括弧内に"array"環境を展開する
        % {c|cc}の形で中央揃え、縦線、中央揃え*2の並びに出来る
        \left[\begin{array}{c}
            a & c \\
            b & d \\
        \end{array}\right]
$$

$$
    % "boldsymbol"で太字にしている
    \boldsymbol{Y} =
        % ベクトルや行列は"left["と"right]"でベクトルや行列の括弧を作る
        % 括弧内に"array"環境を展開する
        % {c|cc}の形で中央揃え、縦線、中央揃え*2の並びに出来る
        \left[\begin{array}{c}
            e & g \\
            f & h \\
        \end{array}\right]
$$

とあった場合

$$
    % "boldsymbol"で太字にしている
    \boldsymbol{X * Y} =
        % ベクトルや行列は"left["と"right]"でベクトルや行列の括弧を作る
        % 括弧内に"array"環境を展開する
        % {c|cc}の形で中央揃え、縦線、中央揃え*2の並びに出来る
        \left[\begin{array}{c}
            a * e + c * f & a * g + c * h \\
            b * e + d * f & b * g + d *h \\
        \end{array}\right]
$$



In [2]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [3]:
# 問題2
print(np.matmul(a_ndarray, b_ndarray))
print(np.dot(a_ndarray, b_ndarray))
print(a_ndarray @ b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [4]:
# 問題4 関数
def compute_matrix_multiplication(a_ndarray, b_ndarray):
    num_of_a_rows, num_of_a_columns = np.shape(a_ndarray)
    num_of_b_rows, num_of_b_columns = np.shape(b_ndarray)
    
    if num_of_a_columns != num_of_b_rows:
        raise ValueError("aの配列の列数: {}, bの配列の行数: {} で一致しないため計算できません".format(num_of_a_columns, num_of_b_rows))

    result = np.array([])
    # row単位でloop
    for a_row_index in range(num_of_a_rows):
        column_result = np.array([])
        # row内のcolumnでloop
        for b_column_index in range(num_of_b_columns):
            result = np.append(result, np.sum(a_ndarray[a_row_index] * b_ndarray[:,b_column_index]))
    # aの行とbの列でreshape
    return result.reshape(num_of_a_rows, num_of_b_columns)

In [5]:
# 課題3
print(compute_matrix_multiplication(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [6]:
# 課題4 サンプル
c1_ndarray = np.array([[0, 2, -1], [0, 1, 2]])
c2_ndarray = np.array([[0, 2], [0, 1], [4, 4]])
print(compute_matrix_multiplication(c1_ndarray, c2_ndarray))

c3_ndarray = np.array([[0, 2], [0, 1], [4, 4]])
c4_ndarray = np.array([[1], [3]])
print(compute_matrix_multiplication(c3_ndarray, c4_ndarray))

[[-4. -2.]
 [ 8.  9.]]
[[ 6.]
 [ 3.]
 [16.]]


In [7]:
# 課題5
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print(compute_matrix_multiplication(d_ndarray, e_ndarray))

ValueError: aの配列の列数: 3, bの配列の行数: 2 で一致しないため計算できません

In [8]:
# 問題6 転置とinnerを使った関数
def compute_matrix_multiplication_using_inner(a_ndarray, b_ndarray):
    num_of_a_rows, num_of_a_columns = np.shape(a_ndarray)
    num_of_b_rows, num_of_b_columns = np.shape(b_ndarray)

    result = np.array([])
    # row単位でloop
    for a_row_index in range(num_of_a_rows):
        column_result = np.array([])
        # row内のcolumnでloop
        for b_column_index in range(num_of_b_columns):
            result = np.append(result, np.inner(a_ndarray[a_row_index], b_ndarray[:,b_column_index].T))
    # aの行とbの列でreshape
    return result.reshape(num_of_a_rows, num_of_b_columns)

In [9]:
print(compute_matrix_multiplication_using_inner(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
