In [39]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


#### 問題1

Pandas
 - pandas.DataFrame()

matplotlib
 - matplotlib.figure.Figure

scikit-learn
 - sklearn.linear_model.LinearRegression
 - sklearn.svm.SVR

#### 問題2

メソッド
- numpyのsort    
- pandasのisnull()
- pandasのloc()

インスタンス変数
- pandasのcolumns
- numpyのdtype

In [51]:
# 問題3
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """

        self.mean_ = np.mean(X, axis=0)
        self.var_ =np.var(X, axis=0)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特徴量
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled



In [52]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [74]:
# 問題4
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.__validate(value)

        self.value = value
        print("初期値{}が設定されました".format(self.value))

    def add(self, value2):
        self.__validate(value2)
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
        
    def substract(self, value2):
        self.__validate(value2)
        """
        受け取った引数をself.valueに加える
        """
        self.value -= value2

    def multiply(self, value2):
        self.__validate(value2)
        """
        受け取った引数をself.valueに加える
        """
        self.value *= value2

    def devide(self, value2):
        self.__validate(value2)
        """
        受け取った引数をself.valueに加える
        """
        self.value /= value2
        
    def __validate(self, value):
        if type(value) is not int:
            raise ValueError("数値を入力してください")
        

example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.substract(2)
print("value : {}".format(example.value))
example.multiply(5)
print("value : {}".format(example.value))
example.devide(4)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8
value : 6
value : 30
value : 7.5


ValueError: 数値を入力してください

In [75]:
# validation check 文字列の場合
ExampleClass("ss")

ValueError: 数値を入力してください

In [78]:
# validation check 配列の場合
ExampleClass([1])

ValueError: 数値を入力してください

In [80]:
# validation check メソッドの引数に数値でない値を設定した場合
example = ExampleClass(5)
example.add("s")

初期値5が設定されました


ValueError: 数値を入力してください